spring:
  application:
    name: service-registry

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: ${CONFIG_SERVER_URIS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URLS}

